version: '3'

services:
  client-demo-app:
    build: ./client/
    #environment:
    #  - URI=http://172.32.0.3:5555
    network_mode: "service:wireguard-client"

  wireguard-client:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
      - PEERDNS=auto
    volumes:
      - ./wg-client-config/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
